### ISSUE TITLE
引入工程后不能识别godeye

### ISSUE THREAD

**Issue by testerclub** [Kyson/AndroidGodEye#18]
引入工程后，报godeye相关的class不能识别，不知道哪里姿势不对。这些install的class都是红色
GodEye.instance().install(Cpu.class, new CpuContextImpl())
                .install(Battery.class, new BatteryContextImpl(this))
                .install(Fps.class, new FpsContextImpl(this))
                .install(Heap.class, Long.valueOf(2000))
                .install(Pss.class, new PssContextImpl(this))
                .install(Ram.class, new RamContextImpl(this))
                .install(Sm.class, new SmContextImpl(this, 1000, 300, 800))
                .install(Traffic.class, new TrafficContextImpl())
                .install(Crash.class, new CrashFileProvider(this))
                .install(ThreadDump.class, new ThreadContextImpl())
                .install(DeadLock.class, new DeadLockContextImpl(GodEye.instance().getModule(ThreadDump.class).subject(), new DeadlockDefaultThreadFilter()))
                .install(Pageload.class, new PageloadContextImpl(this))
                .install(LeakDetector.class, new LeakContextImpl2(this, new PermissionRequest() {
                    @Override
                    public Observable<Boolean> dispatchRequest(Activity activity, String... permissions) {
                        return new RxPermissions(activity).request(permissions);
                    }
                }));

**Comment by Kyson** [comment]
使用了哪个版本？

**Comment by testerclub** [comment]
1.7.3

**Comment by testerclub** [comment]
是不是我引入的方式不对，我是严格按照md文档里引入的

**Comment by Kyson** [comment]
@testerclub 你可以看下demo的接入：https://github.com/Kyson/AndroidGodEyeDemo

**Comment by testerclub** [comment]
好的，谢谢
建议大神建一个Androidgodeye QQ群吧
