### ISSUE TITLE
打成release包的时候，依赖添加为cn.hikyson.godeye:godeye-monitor:1.7.4，包运行后能打开监控界面，却无法获取监控数据？

### ISSUE THREAD

**Issue by ElesG** [Kyson/AndroidGodEye#20]
打成release包的时候，依赖添加为cn.hikyson.godeye:godeye-monitor:1.7.4，包运行后能打开监控界面，却无法获取监控数据？
打成debug包才可以读取到数据，请问是release包有什么限制吗？

**Comment by Kyson** [comment]
不正常的，你的gradle依赖怎么写的

**Comment by ElesG** [comment]
写成这样：
`dependencies{
       implementation 'cn.hikyson.godeye:godeye-core:1.7.4'
        debugImplementation 'cn.hikyson.godeye:godeye-monitor:1.7.4'
        releaseImplementation 'cn.hikyson.godeye:godeye-monitor:1.7.4'
        implementation 'cn.hikyson.godeye:godeye-toolbox:1.7.4'
}`

**Comment by ElesG** [comment]
写成这样：
```
dependencies{
       implementation 'cn.hikyson.godeye:godeye-core:1.7.4'
        debugImplementation 'cn.hikyson.godeye:godeye-monitor:1.7.4'
        releaseImplementation 'cn.hikyson.godeye:godeye-monitor:1.7.4'
        implementation 'cn.hikyson.godeye:godeye-toolbox:1.7.4'
}
```

**Comment by Kyson** [comment]
依赖没啥问题，有报什么错吗

**Comment by Leessy** [comment]
混淆有要注意的地方吗？

**Comment by Kyson** [comment]
@ElesG 时间太久close了哈
