### ISSUE TITLE
pss

### ISSUE THREAD

**Issue by testerclub** [Kyson/AndroidGodEye#21]

**Comment by testerclub** [comment]
您好，我在demo里启用AndroidGodeye后，通过5390端口查看到的PSS值与Android Profiler显示的memory total值相比有近200m的差异，AndroidGodeye 的pss值为600+，相同时间Android Profiler显示的memory才400+，这两者有这么大的差异，原因可能会是哪些呢？

**Comment by Kyson** [comment]
这个我暂不清楚，但是两者的内存应该不是同一个概念或者不是一个计算方式。
