### ISSUE TITLE
LeakObject不显示

### ISSUE THREAD

**Issue by qsjh898** [Kyson/AndroidGodEye#22]
我直接在手机上安装了demo，通过JUMPTOLEAK进行内存泄漏的测试，但是WEB页面上只显示出了内存泄露的记录

![snipaste_2018-03-01_17-14-15](https://user-images.githubusercontent.com/17870052/36836755-32f3829e-1d75-11e8-9941-42b7149e7d72.png)

我手机是华为Mate S，系统是Android5.1.1

**Comment by Kyson** [comment]
点击一下左边的箭头:-)

**Comment by Kyson** [comment]
点箭头之前先右上角点一下停止，否则表格会刷新，自动收起详情

**Comment by qsjh898** [comment]
![snipaste_2018-03-01_17-14-15](https://user-images.githubusercontent.com/17870052/36879449-e242652e-1dfe-11e8-8f7f-1a04d55287cf.png)
停止了之后展开还是空的

**Comment by Kyson** [comment]
@qsjh898 检测泄漏的过程比较漫长，可以看下status状态，leak detected只是说检测到了泄漏，status done的状态才是已经把泄漏对象等等信息都获取到了
