### ISSUE TITLE
三星Galaxy A5(2016) 运行Demo，进入内存泄漏界面后退出，程序崩溃

### ISSUE THREAD

**Issue by qsjh898** [Kyson/AndroidGodEye#23]
![snipaste_2018-03-08_10-01-46](https://user-images.githubusercontent.com/17870052/37129044-f3f78b9c-22b7-11e8-94ba-3b7026743978.png)

**Comment by Kyson** [comment]
应该是你调用安装的进程不对，具体看下demo怎么调用的安装吧

**Comment by Kyson** [comment]
@qsjh898 不好意思，leak canary安装必须在主进程，具体可以看下2.x版本,也就是当前的readme
