### ISSUE TITLE
demo浏览器面板出不来

### ISSUE THREAD

**Issue by fengdongfei** [Kyson/AndroidGodEye#3]
连上的是同一个无线网，我用的是http://手机ip地址:5390,但是打不开面板，怎么回事呢？还有installAll这个函数和readme不一样了，多了个参数，如何使用呢？？

**Comment by Kyson** [comment]
确认一下手机的网段和pc是不是同一个。最好是同一个路由器的wifi下

**Comment by Kyson** [comment]
可以先用这个demo试一下：https://fir.im/5k67，确认本地通信没问题
