### ISSUE TITLE
RxPermissionsFragment 冲突

### ISSUE THREAD

**Issue by JesseWo** [Kyson/AndroidGodEye#30]
初始化时, 这行代码 `.install(new LeakConfig(this,new RxPermissionRequest()))`导致crash, 必现.
`com.tbruyelle.rxpermissions2.RxPermissionsFragment cannot be cast to cn.hikyson.android.godeye.toolbox.rxpermission.RxPermissionsFragment
`
我项目中使用了[RxPermissions](https://github.com/tbruyelle/RxPermissions);

**Comment by Kyson** [comment]
理论上这是两个不同的类，不会有问题的，如果不想用toolbox中的权限请求，可以自己实现一个PermissionRequest，类似RxPermissionRequest这样：

public class RxPermissionRequest implements PermissionRequest {
    @Override
    public Observable<Boolean> dispatchRequest(Activity activity, String... permissions) {
        return new RxPermissions(activity).request(permissions);
    }
}

**Comment by Kyson** [comment]
@JesseWo 新版本删了这个类，理论上没有模块需要敏感权限...
