### ISSUE TITLE
(BUG AndroidGodEye version 6.0 ) The Application crashes when i click on Block option 

### ISSUE THREAD

**Issue by friendsmobile** [Kyson/AndroidGodEye#43]
# Project Information

* Repository:  https://github.com/Kyson/AndroidGodEye
* Project Name: AndroidGodEye
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://fir.im/5k67

# Expected behavior

after opening the application when I click on Block option the Application should not crash 

# Actual behavior

 The Application crashes when I click on Block option 

#### How to reproduce

* [Download ](https://fir.im/5k67)the application
*  open the Application
* click on BLOCK option
* Note the Error

* Browser/App version:  6.0
* Operating system: 6.0

#### Recording Of The Bug

![20190723_144739](https://user-images.githubusercontent.com/51118734/61702479-b3336b80-acf4-11e9-87a2-bb0c5b6af246.gif)

#### Logcat

<pre><code>E/AndroidRuntime(19687): FATAL EXCEPTION: main

E/AndroidRuntime(19687): Process: cn.hikyson.godeyedemo, PID: 19687

E/AndroidRuntime(19687): java.lang.IllegalStateException: Could not execute method of the activity

E/AndroidRuntime(19687): 	at android.view.View$1.onClick(View.java:4135)

E/AndroidRuntime(19687): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(19687): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(19687): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(19687): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(19687): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(19687): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(19687): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(19687): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(19687): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(19687): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(19687): Caused by: java.lang.reflect.InvocationTargetException

E/AndroidRuntime(19687): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(19687): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(19687): 	at android.view.View$1.onClick(View.java:4130)

E/AndroidRuntime(19687): 	... 10 more

E/AndroidRuntime(19687): Caused by: java.lang.NumberFormatException: Invalid long: ""

E/AndroidRuntime(19687): 	at java.lang.Long.invalidLong(Long.java:124)

E/AndroidRuntime(19687): 	at java.lang.Long.parseLong(Long.java:345)

E/AndroidRuntime(19687): 	at java.lang.Long.parseLong(Long.java:321)

E/AndroidRuntime(19687): 	at cn.hikyson.godeyedemo.MainActivity.block(MainActivity.java:92)
</code></pre>

**Comment by Kyson** [comment]
Sorry for this bug. I know it is not reasonable but you must input a number in EditText, then click the block Button, hope helpful :-)

**Comment by friendsmobile** [comment]
yes  your are right this is not bug thanks your feedback

**Comment by Kyson** [comment]
Anyway ,i fix it in the latest version, thx for your feedback
