### ISSUE TITLE
The image is broken or  blurry on README

### ISSUE THREAD

**Issue by DysaniazzZ** [Kyson/AndroidGodEye#47]
The image below `Base info` and `More` is broken and the image below `Framework` is too blurry to figure out.

**Comment by Kyson** [comment]
@DysaniazzZ Thx a lot, i will fix it~

**Comment by DysaniazzZ** [comment]
the image below `Framework` is still blurry, I can't figure out.

**Comment by DysaniazzZ** [comment]
BTW, does the cpu monitor support multiple process application?

**Comment by Kyson** [comment]
@DysaniazzZ I think is not, because 'CPU data' is read from file:"/proc/pid/stat" which is  process isolated

**Comment by DysaniazzZ** [comment]
@Kyson ok, thx for your reply.
