### ISSUE TITLE
can't resolve the newest plugin

### ISSUE THREAD

**Issue by DysaniazzZ** [Kyson/AndroidGodEye#48]
ERROR: Failed to resolve: cn.hikyson.godeye:godeye-monitor:2.7.3
Show in Project Structure dialog

ERROR: Failed to resolve: cn.hikyson.godeye:godeye-core:2.7.3
Show in Project Structure dialog

ERROR: Failed to resolve: cn.hikyson.godeye:godeye-toolbox:2.7.3
Show in Project Structure dialog

ERROR: Failed to resolve: cn.hikyson.godeye:godeye-monitor-no-op:2.7.3
Show in Project Structure dialog

**Comment by Kyson** [comment]
@DysaniazzZ 2.7.3 Build failed. please use 2.7.2, i will fix it soon.

**Comment by DysaniazzZ** [comment]
@Kyson ok, I will try, thx.
