### ISSUE TITLE
application初始化需要传入provider？

### ISSUE THREAD

**Issue by kinzirva** [Kyson/AndroidGodEye#5]
GodEye.instance().installAll(getApplication())
code文档里面并没有需要传入provider这个类

**Comment by kinzirva** [comment]
GodEye.instance().installAll(getApplication(), new CrashProvider() {
            @Override
            public void storeCrash(CrashInfo crashInfo) throws Throwable {

            }

            @Override
            public List<CrashInfo> restoreCrash() throws Throwable {
                return null;
            }
        });
        GodEyeMonitor.work(getApplicationContext());
这样按照code文档执行后，ip+端口一直拒绝访问

**Comment by Kyson** [comment]
readme稍后更新，如果一直无法看到看板的话，先试一下这个demo：https://fir.im/5k67
确认本地通信没问题之后再看看接入

**Comment by kinzirva** [comment]
demo  apk 是可以监控到的。
咱们sample里面的例子也没有用到 code文档里面的初始化buzhu啊

**Comment by Kyson** [comment]
文档已经更新，crashprovider如果没有特殊需求的话使用toolbox中的即可
