### ISSUE TITLE
Method canary chart is not user friendly

### ISSUE THREAD

**Issue by ahhbzyz** [Kyson/AndroidGodEye#50]
![image](https://user-images.githubusercontent.com/15330335/63749482-1f9a1f80-c8de-11e9-99e4-c32d63a5fb04.png)

1. The mouse gesture in the chart is not intuitive
2. The package name shown in the chart could be omitted

**Comment by Kyson** [comment]
done @ahhbzyz

**Comment by ahhbzyz** [comment]
Extremely good!
