### ISSUE TITLE
希望能提供一套代码同步到最新的非androidx库

### ISSUE THREAD

**Issue by liuleshuai** [Kyson/AndroidGodEye#65]
还有个建议，引入该库的同时，会将rxjava2也引进来，这点不太友好

**Comment by Kyson** [comment]
@liuleshuai 谢谢你的建议，不过现在大部分开源库都迁移到了androidx，项目迁移androidx其实也很方便的，所以这个建议暂时还不会考虑

rxjava的引入的确会影响库的size，主要还是这个库太方便了。。而且我大量用了这个库，所以改造成本不小，所以暂时也不会安排改造

谢谢
