### ISSUE TITLE
THREAD的数据消费时会crash

### ISSUE THREAD

**Issue by BetterIgor** [Kyson/AndroidGodEye#66]
GodEye.instance().observeModule(GodEye.ModuleName.THREAD, new Consumer<ThreadInfo>() {
            @Override
            public void accept(ThreadInfo threadInfo) throws Exception {
                mConsumer.accept(GodEye.ModuleName.THREAD, threadInfo);
            }
        });

03-20 04:23:17.341 16128 16148 E AndroidRuntime: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.util.ArrayList cannot be cast to cn.hikyson.methodcanary.lib.ThreadInfo
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to cn.hikyson.methodcanary.lib.ThreadInfo
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at com.douban.frodo.eye.Eye$18.accept(Eye.java:187)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
03-20 04:23:17.341 16128 16148 E AndroidRuntime: 	... 9 more

**Comment by Kyson** [comment]
Consumer中的范型使用List<Threadinfo>

**Comment by BetterIgor** [comment]
fixed，🙏

**Comment by BetterIgor** [comment]
可以共享下AndroidStudio的AndroidGodEye插件源码吗？想做一个整体分析的可视化界面，如果功能的话做起来快一些，嘻嘻

**Comment by Kyson** [comment]
项目里有的，插件代码很简单，就是打开浏览器而已

**Comment by BetterIgor** [comment]
好的，我找找。🙏
