### ISSUE TITLE
Is there a library that support can use?

### ISSUE THREAD

**Issue by e9ab98e991ab** [Kyson/AndroidGodEye#68]
Now the support is still used in the project, there is currently no way to upgrade androidx。Ask support, which version is available

**Comment by Kyson** [comment]
You can use version 3.1.2 if ur project has not been transfered to androidx

Details:
https://github.com/Kyson/AndroidGodEye/wiki/0x00-QuickStart_zh

https://github.com/Kyson/AndroidGodEye/wiki/0x00-QuickStart_en
