### ISSUE TITLE
MethodCanaryTransform This feature requires ASM6

### ISSUE THREAD

**Issue by muxi166** [Kyson/AndroidGodEye#70]
Execution failed for task ':app:transformClassesWithMethodCanaryTransformForDebug'.
> This feature requires ASM6

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.

**Comment by Kyson** [comment]
Ok, i will check it in  few days.

**Comment by Kyson** [comment]
@muxi166 Can you show me the gradle-wrapper.properties and  Android Gradle Tool version like
classpath 'com.android.tools.build:gradle:VERSION'

I tried to reproduce the problem but it no problem been found.

**Comment by Kyson** [comment]
@muxi166 Any more updates?

**Comment by muxi166** [comment]
> @muxi166 Can you show me the gradle-wrapper.properties and Android Gradle Tool version like
> classpath 'com.android.tools.build:gradle:VERSION'
> 
> I tried to reproduce the problem but it no problem been found.

3.4.2

**Comment by Kyson** [comment]
Merge refer to [https://github.com/Kyson/AndroidGodEye/issues/72](https://github.com/Kyson/AndroidGodEye/issues/72)
