### ISSUE TITLE
 Please install method canary first! 

### ISSUE THREAD

**Issue by xuduo** [Kyson/AndroidGodEye#71]
![image](https://user-images.githubusercontent.com/1247293/82009117-0a9a3200-96a1-11ea-8d99-d8a55b71e938.png)
My project is multi-leveled
I have added 
```
apply plugin: 'cn.hikyson.methodcanary.plugin'

AndroidGodEye {
    enableLifecycleTracer true
    enableMethodTracer true
    instrumentationRuleFilePath "AndroidGodEye-MethodCanary.js"
    instrumentationRuleIncludeClassNamePrefix(["cn/hikyson/godeye/sample"])
}
```
in Application Module Project

**Comment by Kyson** [comment]
@xuduo Sorry i missed some instructions and it has been added now:

[0x00-QuickStart_en](https://github.com/Kyson/AndroidGodEye/wiki/0x00-QuickStart_en)

![image](https://user-images.githubusercontent.com/3901140/82014217-be55ee80-96ae-11ea-9ec9-1ecb8a4e906e.png)

**Comment by xuduo** [comment]
OK, it works!
