### ISSUE TITLE
there is nothing for 3.1.2 about godeye-xcrash and godeye-leakcanary

### ISSUE THREAD

**Issue by Rocketer2018** [Kyson/AndroidGodEye#74]
Could not resolve cn.hikyson.godeye:godeye-leakcanary:3.1.2：
![image](https://user-images.githubusercontent.com/45086517/82637501-7fd4ac80-9c37-11ea-9f22-0ad42cc737b4.png)
Could not resolve cn.hikyson.godeye:godeye-xcrash:3.1.2：
![image](https://user-images.githubusercontent.com/45086517/82637511-8531f700-9c37-11ea-8611-1a44d87f8b06.png)

but you say  其次你的项目需要迁移至androidx，从版本3.1.3开始AndroidGodEye迁移到了androidx，如果你的项目没有使用androidx，那么只能使用3.1.2及以下版本:
![image](https://user-images.githubusercontent.com/45086517/82637572-a7c41000-9c37-11ea-99dd-5223628ba05e.png)

and 3.1.1、3.1.0 is same to 3.1.2

**Comment by Rocketer2018** [comment]
there is nothing in 3.1.2 about crash and leakcanary

**Comment by Kyson** [comment]
@Rocketer2018 I just added instructions of 3.1.2: https://github.com/Kyson/AndroidGodEye/wiki/0x00a-QuickStart_3.1.2_legacy_zh

**Comment by taishuhongye** [comment]
OK👌。and。。。。。。：

![image](https://user-images.githubusercontent.com/45086517/82875942-a6ae1e00-9f6a-11ea-91ed-5599c974e03b.png)

**Comment by Kyson** [comment]
Just use 'javascript', for example:

```javascript
return classInfo.name.startWith('cn/demo') || methodInfo.name.startWith('androidgodeye')
```

**Comment by taishuhongye** [comment]
i know js,my mean,there s more ")" in wiki

**Comment by Kyson** [comment]
:-) Thank u ...
