### ISSUE TITLE
Not able to use tool / open Dashboard

### ISSUE THREAD

**Issue by ramgiteng** [Kyson/AndroidGodEye#77]
Hello,

I created a project on Android studio and performed the following.
1) Made modifications to the build.gradle on root level and build.gradle on project level by including the dependencies
2) Created an /assets folder and included install.config. 
3) Created an AndroidGodEye-MethodCanary.js at root level.
4) Installed the AndroidGodEye plugin in Android studio and provided the port number.

After starting AndroidGodEye dashboard from plugin in Android studio, I am unable to connect. 

Do we need to mention the .apk file that is being tested anywhere?
Is there anything more that I would need to do to use this tool to monitor the Android app?

**Comment by Kyson** [comment]
1. What is the version of AndroidGodEye?
2. You should follow the steps of this post: https://github.com/Kyson/AndroidGodEye/wiki/0x00-QuickStart_en
3. If it still did't work, show me your source code.
Thx.

**Comment by ramgiteng** [comment]
@Kyson 
Thanks for the reply. I have followed all of your steps. The version I am using is 3.4.3 I will share the code in my next reply.

**Comment by Kyson** [comment]
@rameshgit96 
1. Run your project and show me the logcat, filter:"AndroidGodEye" 
2. Make sure no conflicts on the monitor port, default is 5390
3. run 'adb devices' and show me the output

Thx.
