### ISSUE TITLE
如何保存或导出历史数据？

### ISSUE THREAD

**Issue by icesword0760** [Kyson/AndroidGodEye#82]
作者你好！
想问一下，如果我想保存历史数据到本地或者导出；需要如何做？
例如，我想导出过去2小时的cpu和内存使用数据

**Comment by Kyson** [comment]
现在没有现成的功能，不过你可以自己监听模块的数据自己保存起来 方式类似这个文档中的描述： https://github.com/Kyson/AndroidGodEye/wiki/0x02b-Apply-AndroidGodEye-for-Release_zh
