### ISSUE TITLE
Compatible with IntelliJ IDEA only

### ISSUE THREAD

**Issue by Aracoix** [Kyson/AndroidGodEye#84]
![image](https://user-images.githubusercontent.com/7815748/141926280-c936e53b-c9bc-4ed1-a428-9fe3171a0537.png)
![image](https://user-images.githubusercontent.com/7815748/141926331-dc940a34-48b9-475f-b8e6-885457e8135f.png)
![image](https://user-images.githubusercontent.com/7815748/141926558-0d2a614c-3e3a-4b22-b365-a1968c7dd9da.png)

**Comment by Kyson** [comment]
![image](https://user-images.githubusercontent.com/3901140/148008323-fc6b1ed0-9241-4c86-bb1c-3c0f58c73a68.png)

This plugin is compatible with Android Studio

If you can't make it, try to change to this way: [https://github.com/Kyson/AndroidGodEye/wiki/0x02a-DebugMonitor_en#debugmonitor-dashboard](https://github.com/Kyson/AndroidGodEye/wiki/0x02a-DebugMonitor_en#debugmonitor-dashboard)
