### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by febiAlfarabi** [Kyson/AndroidGodEye#9]
Hai.. thanks for who make this an awesome tools to monitor resource usage in Android, but i wonder how to see an English translation in this monitoring tools, thanks in advance.

**Comment by Kyson** [comment]
okay..i will consider your suggestion.
thank you .

**Comment by Kyson** [comment]
It will be resolved tomorrow.

**Comment by febiAlfarabi** [comment]
@Kyson youre an awesome, i will wait that. Thank you :D

**Comment by Kyson** [comment]
done.
thx.
